title: 'Matt Millican'
author: 'Matt Millican'
subtitle: 'Milwaukee Web Developer'

twitter_username: millicanmatt
github_username:  mmillican
stackoverflow_link: users/976042/matt-millican

markdown: kramdown
highlighter: rouge

disqus: mattmillican