title: 'Matt Millican'
author: 'Matt Millican'
subtitle: 'Web Developer. Photographer. Geek at heart.'
description: Web Developer specializing in ASP.NET Core

feed_url: /feed.xml
twitter_username: millicanmatt
github_username:  mmillican
stackoverflow_link: users/976042/matt-millican
flickr_username: mattmillican
linkedin_username: mattmillican

twitter:
  username: millicanmatt
  card: summary


markdown: kramdown
highlighter: rouge

disqus: mattmillican

plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag