title: 'Matt Millican'
author: 'Matt Millican'
subtitle: 'Web Developer. Photographer. Geek at heart.'

twitter_username: millicanmatt
github_username:  mmillican
stackoverflow_link: users/976042/matt-millican
flickr_username: mattmillican
linkedin_username: mattmillican

markdown: kramdown
highlighter: rouge

disqus: mattmillican

plugins:
  - jekyll-redirect-from