title: 'Matt Millican'
author: 'Matt Millican'
subtitle: 'All things dev, cloud and learning'
description: Web Developer specializing in ASP.NET Core
header-img: 'img/header-bg.jpg'

feed_url: /feed.xml
twitter_username: millicanmatt
github_username:  mmillican
stackoverflow_link: users/976042/matt-millican
flickr_username: mattmillican
linkedin_username: mattmillican

twitter:
  username: millicanmatt
  card: summary

sass:
  sass_dir: _sass
  style: compressed

markdown: kramdown
highlighter: rouge

disqus: mattmillican

plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag